// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: gateway/service.proto

package gateway

import (
	core "github.com/kappa-lab/grpc-playground/import-sandbox/pb/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_service_proto protoreflect.FileDescriptor

const file_gateway_service_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/service.proto\x12\agateway\x1a\x10core/model.proto\x1a\x13gateway/model.proto2B\n" +
	"\x0eGatewayService\x120\n" +
	"\x04Auth\x12\x14.gateway.AuthRequest\x1a\x12.core.UserResponse2?\n" +
	"\vUserService\x120\n" +
	"\aGetUser\x12\x11.core.UserRequest\x1a\x12.core.UserResponseB@Z>github.com/kappa-lab/grpc-playground/import-sandbox/pb/gatewayb\x06proto3"

var file_gateway_service_proto_goTypes = []any{
	(*AuthRequest)(nil),       // 0: gateway.AuthRequest
	(*core.UserRequest)(nil),  // 1: core.UserRequest
	(*core.UserResponse)(nil), // 2: core.UserResponse
}
var file_gateway_service_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.Auth:input_type -> gateway.AuthRequest
	1, // 1: gateway.UserService.GetUser:input_type -> core.UserRequest
	2, // 2: gateway.GatewayService.Auth:output_type -> core.UserResponse
	2, // 3: gateway.UserService.GetUser:output_type -> core.UserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_service_proto_init() }
func file_gateway_service_proto_init() {
	if File_gateway_service_proto != nil {
		return
	}
	file_gateway_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_service_proto_rawDesc), len(file_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gateway_service_proto_goTypes,
		DependencyIndexes: file_gateway_service_proto_depIdxs,
	}.Build()
	File_gateway_service_proto = out.File
	file_gateway_service_proto_goTypes = nil
	file_gateway_service_proto_depIdxs = nil
}
