// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: core/service.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_service_proto protoreflect.FileDescriptor

const file_core_service_proto_rawDesc = "" +
	"\n" +
	"\x12core/service.proto\x12\x04core\x1a\x10core/model.proto2\xa9\x01\n" +
	"\vUserService\x123\n" +
	"\n" +
	"CreateUser\x12\x11.core.UserRequest\x1a\x12.core.UserResponse\x120\n" +
	"\aGetUser\x12\x11.core.UserRequest\x1a\x12.core.UserResponse\x123\n" +
	"\n" +
	"DeleteUser\x12\x11.core.UserRequest\x1a\x12.core.UserResponseB=Z;github.com/kappa-lab/grpc-playground/import-sandbox/pb/coreb\x06proto3"

var file_core_service_proto_goTypes = []any{
	(*UserRequest)(nil),  // 0: core.UserRequest
	(*UserResponse)(nil), // 1: core.UserResponse
}
var file_core_service_proto_depIdxs = []int32{
	0, // 0: core.UserService.CreateUser:input_type -> core.UserRequest
	0, // 1: core.UserService.GetUser:input_type -> core.UserRequest
	0, // 2: core.UserService.DeleteUser:input_type -> core.UserRequest
	1, // 3: core.UserService.CreateUser:output_type -> core.UserResponse
	1, // 4: core.UserService.GetUser:output_type -> core.UserResponse
	1, // 5: core.UserService.DeleteUser:output_type -> core.UserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_service_proto_init() }
func file_core_service_proto_init() {
	if File_core_service_proto != nil {
		return
	}
	file_core_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_proto_goTypes,
		DependencyIndexes: file_core_service_proto_depIdxs,
	}.Build()
	File_core_service_proto = out.File
	file_core_service_proto_goTypes = nil
	file_core_service_proto_depIdxs = nil
}
